import Head from 'next/head'

const Header = () => {
  return (
    <div>
      <Head>
        <title>SHConnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Header</h1>
      </div>
    </div>
  )
}
export default Header;